# https://pre-commit.com/hooks.html
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
      - id: requirements-txt-fixer
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - "--ignore=E501,F401,E266,F811,W503,F841"
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  # - repo: "https://github.com/asottile/dead"
  #   rev: v1.4.0
  #   hooks:
  #   -   id: dead
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/bandit
    rev: '1.7.4'
    hooks:
    -   id: bandit
        exclude: tests/
