# https://pre-commit.com/hooks.html
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
      - id: requirements-txt-fixer
  # - repo: local
  #   hooks:
  #     - id: django-check
  #       name: Check django project for potential problems
  #       entry: sh -c 'python manage.py check'
  #       types:
  #         - python
  #       pass_filenames: false
  #       language: system
  #     - id: django-check-migrations
  #       name: Check django project for missing migrations.
  #       entry: sh -c 'python manage.py makemigrations --check --dry-run'
  #       files: models.py
  #       types:
  #         - python
  #       pass_filenames: false
  #       language: system
  # - repo: 'https://gitlab.com/pycqa/flake8'
  #   rev: 3.9.0
  #   hooks:
  #     - id: flake8
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.8.0
    hooks:
      - id: isort
  # - repo: "https://github.com/asottile/dead"
  #   rev: v1.4.0
  #   hooks:
  #   -   id: dead
  # - repo: 'https://github.com/python/black'
  #   rev: 20.8b1
  #   hooks:
  #     - id: black
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #   rev: v1.0.5
  #   hooks:
  #   -   id: python-bandit-vulnerability-check

