language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements/requirements.txt
# command to run tests
script:
  - python tests/test_auth.py
  - pytest tests/test_collaboration.py
  - pytest tests/test_costs.py
  - pytest tests/test_deliverables.py
  - pytest tests/test_invoicing.py
  - pytest tests/test_others.py
  - pytest tests/test_settings.py
  - pytest tests/test_time.py